# Generated by Django 2.1.4 on 2018-12-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='lug required', unique=True),
            preserve_default=False,
        ),
    ]
