# Generated by Django 2.1.4 on 2018-12-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
